version: '3.2'

services:
  
  ap1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /usr/src/app/dev-entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 4000:4000
    networks:
      - app-network
      
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: /usr/src/app/dev-entrypoint.sh
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:80
    networks:
      - app-network
            
networks:
  app-network:      