version: '3.2'

services:
      
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: /usr/src/app/dev-entrypoint.sh
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:80
    networks:
      - app-network
            
networks:
  app-network:      