---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: frontend
          image: elvizcacho/juaapp-frontend:latest
          resources:
            requests:
              memory: 50Mi
              cpu: 25m
            limits:
              memory: 100Mi
              cpu: 50m
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred