export const FETCH_BANK_ENTRIES = 'FETCH_BANK_ENTRIES'
export const RECEIVE_BANK_ENTRIES = 'RECEIVE_BANK_ENTRIES'
export const SELECT_BANK_ENTRY_CATEGORY = 'SELECT_BANK_ENTRY_CATEGORY'
export const UNSELECT_BANK_ENTRY_CATEGORY = 'UNSELECT_BANK_ENTRY_CATEGORY'