---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdfs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdfs
    spec:
      containers:
        - name: frontend
          image: elvizcacho/juaapp-pdfs:latest
          ports:
            - containerPort: 4100
          imagePullPolicy: Always
          resources:
            requests:
              memory: 50Mi
              cpu: 25m
            limits:
              memory: 100Mi
              cpu: 50m
      imagePullSecrets:
        - name: regcred